In [4]:
print('CODING ATTENTION MECHANISM')

CODING ATTENTION MECHANISM


In [5]:
import torch
inputs=torch.tensor(torch.rand(6,4))
inputs

/var/folders/hp/y1d826dx5fb1405ppnjjm4700000gn/T/ipykernel_4906/935272016.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  inputs=torch.tensor(torch.rand(6,4))


tensor([[0.8398, 0.8042, 0.1213, 0.5309],
        [0.6646, 0.4077, 0.0888, 0.2429],
        [0.7053, 0.6216, 0.9188, 0.0185],
        [0.8741, 0.0560, 0.9659, 0.0073],
        [0.3628, 0.4197, 0.6444, 0.0099],
        [0.5925, 0.9631, 0.6958, 0.9157]])

In [6]:
# finding z3 a context vector for fourth token

query4=inputs[3]
query4 @ inputs.T  # 1x4  @   6x4 ------>  1x4 @ 4x6 = 1x6  

tensor([0.9002, 0.6913, 1.5390, 1.7004, 0.9632, 1.2506])

In [7]:
#majddori method 


query4=inputs[3]
attention_score_4=torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attention_score_4[i]=torch.dot(x_i,query4)
print(attention_score_4,attention_score_4.shape)    
    



tensor([0.9002, 0.6913, 1.5390, 1.7004, 0.9632, 1.2506]) torch.Size([6])


In [8]:
for i in inputs:
    print(i)

tensor([0.8398, 0.8042, 0.1213, 0.5309])
tensor([0.6646, 0.4077, 0.0888, 0.2429])
tensor([0.7053, 0.6216, 0.9188, 0.0185])
tensor([0.8741, 0.0560, 0.9659, 0.0073])
tensor([0.3628, 0.4197, 0.6444, 0.0099])
tensor([0.5925, 0.9631, 0.6958, 0.9157])


In [9]:
majduri_dot_product=0
for idx,element in enumerate(inputs[0]):
    majduri_dot_product+=inputs[0][idx] * query4[idx]
print(majduri_dot_product)
print(torch.dot(inputs[0],query4))



tensor(0.9002)
tensor(0.9002)


In [10]:
#normalizing 

attn_weights_4_normlaized = attention_score_4 / attention_score_4.sum()
print(f'Attention scores without normalization : {attention_score_4}')
print(f'Attention score with normalization     : {attn_weights_4_normlaized}')

Attention scores without normalization : tensor([0.9002, 0.6913, 1.5390, 1.7004, 0.9632, 1.2506])
Attention score with normalization     : tensor([0.1278, 0.0981, 0.2185, 0.2414, 0.1367, 0.1775])


In [11]:
attn_weights_4_normlaized.sum()

tensor(1.)

In [12]:
# applying softmax instead of normalization

def naive_softmax(x): 
    print(torch.exp(x).shape) 
    return torch.exp(x)/torch.exp(x).sum(dim=0)

attn_weights_4_sft=naive_softmax(attention_score_4)

attn_weights_4_sft

torch.Size([6])


tensor([0.1188, 0.0964, 0.2251, 0.2645, 0.1265, 0.1687])

In [13]:
attn_weights_4_sft.sum()

tensor(1.0000)

In [14]:
# optimized way by pytorch

attn_weights_4_sft_optzd=torch.softmax(attention_score_4,dim=0)

print(f'Attention weights using softmax by pytorch {attn_weights_4_sft_optzd}')

print(f'Attnetion scores sum is {attn_weights_4_sft_optzd.sum()}')

Attention weights using softmax by pytorch tensor([0.1188, 0.0964, 0.2251, 0.2645, 0.1265, 0.1687])
Attnetion scores sum is 1.0


In [15]:
# okay now we will apply attention scores to their respective vectors and then sum it 

query=inputs[3] #this is the 4th token

context_vec_4=torch.zeros(query.shape)

for i,x_i in enumerate(inputs):
    context_vec_4+=attn_weights_4_sft_optzd[i] * x_i

print(context_vec_4)
    

tensor([0.6997, 0.5051, 0.6841, 0.2483])


In [16]:
torch.matmul(attn_weights_4_sft_optzd,inputs)

tensor([0.6997, 0.5051, 0.6841, 0.2483])

In [17]:
# now calculating for every token in the input 

attention_score_input=torch.empty(6,6)

for i , x_i in enumerate(inputs):
    for j , x_j in enumerate(inputs):
        attention_score_input[i,j]=torch.dot(x_i,x_j)

print(attention_score_input)        

tensor([[1.6485, 1.0258, 1.2135, 0.9002, 0.7257, 1.8426],
        [1.0258, 0.6749, 0.8083, 0.6913, 0.4719, 1.0707],
        [1.2135, 0.8083, 1.7284, 1.5390, 1.1091, 1.6728],
        [0.9002, 0.6913, 1.5390, 1.7004, 0.9632, 1.2506],
        [0.7257, 0.4719, 1.1091, 0.9632, 0.7231, 1.0766],
        [1.8426, 1.0707, 1.6728, 1.2506, 1.0766, 2.6011]])


In [18]:
torch.matmul(inputs,inputs.T)

tensor([[1.6485, 1.0258, 1.2135, 0.9002, 0.7257, 1.8426],
        [1.0258, 0.6749, 0.8083, 0.6913, 0.4719, 1.0707],
        [1.2135, 0.8083, 1.7284, 1.5390, 1.1091, 1.6728],
        [0.9002, 0.6913, 1.5390, 1.7004, 0.9632, 1.2506],
        [0.7257, 0.4719, 1.1091, 0.9632, 0.7231, 1.0766],
        [1.8426, 1.0707, 1.6728, 1.2506, 1.0766, 2.6011]])

In [19]:
attention_score_input_sft_nrmlzd=torch.softmax(attention_score_input,dim=1)

In [20]:
torch.sum(torch.softmax(attention_score_input,dim=1),dim=1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000])

In [21]:
context_vectors=torch.matmul(attention_score_input_sft_nrmlzd,inputs)
context_vectors

tensor([[0.6864, 0.6531, 0.5439, 0.4199],
        [0.6871, 0.5944, 0.5598, 0.3479],
        [0.6851, 0.5683, 0.6572, 0.3041],
        [0.6997, 0.5051, 0.6841, 0.2483],
        [0.6786, 0.5614, 0.6342, 0.2982],
        [0.6703, 0.6960, 0.5966, 0.4804]])

In [22]:
# here we start with trainable matrices with matrix q,k,v
input_vec_token2=inputs[1]

d_in=inputs.shape[1]
d_out=3




In [23]:
import torch.nn 
torch.manual_seed(6969)

w_key=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
w_query=torch.nn.Parameter(torch.rand(d_in,d_out),requires_grad=False)
w_value=torch.nn.Parameter(torch.rand(d_in,d_out,requires_grad=False))

In [24]:
query_2=inputs[1]@w_query
key_2=inputs[1]@w_key
value_2=inputs[1]@w_value

In [25]:
print(query_2)
print(key_2)
print(value_2)


tensor([1.0028, 0.4865, 0.6946])
tensor([0.7034, 0.8019, 0.6788])
tensor([0.8855, 0.8590, 0.4732], grad_fn=<SqueezeBackward4>)


In [26]:
keys=inputs @ w_key #6x4 4x3 ---> 6x3
values=inputs @ w_value#6x4 4x3 ---> 6x3
query=inputs @ w_query #6x4 4x3 ---> 6x3

In [27]:
keys.shape

torch.Size([6, 3])

In [28]:
#now we find attention matrix we use quey vector of that token fow whihc we want to find its corresponding vector

query_2=query[1]

attention_scores2=torch.matmul(query_2,keys.T)  #1x3  @  6x3 ---> 1x6

print(attention_scores2.sum())


tensor(15.9836)


In [29]:
# now we scale the logits first then apply spftmax
attention_scores2=torch.softmax(attention_scores2 / d_out**0.5,dim=0)
ct1=torch.matmul(attention_scores2,values)  #1x6  @6x3-----> 1x3
print(attention_scores2.sum(dim=0))

tensor(1.0000)


In [30]:
ct1

tensor([1.0702, 1.4964, 1.0350], grad_fn=<SqueezeBackward4>)

In [46]:
import torch.nn as nn
class SelfAttention_v1(nn.Module):
    def __init__(self, d_in,d_out):  
        super().__init__()
        self.w_query=nn.Parameter(torch.rand(d_in,d_out))
        self.W_key=nn.Parameter(torch.rand(d_in,d_out))
        self.W_value=nn.Parameter(torch.rand(d_in,d_out))

    def forward(self,x):
        keys= x @ self.W_key   
        print('kdone')         
        queries= x @ self.w_query
        print('qdone') 
        values=x @ self.W_value
        print('vdone') 
        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5 , dim=-1
        )   
        context_vec = attn_weights @ values
        return context_vec
    

In [47]:
import torch
torch.manual_seed(69)

sa_v1=SelfAttention_v1(d_in,d_out)
print(sa_v1(inputs))

kdone
qdone
vdone
tensor([[1.1773, 1.3761, 1.1954],
        [1.0623, 1.2755, 1.0853],
        [1.1467, 1.3518, 1.1668],
        [1.0986, 1.3097, 1.1207],
        [1.0454, 1.2633, 1.0700],
        [1.2563, 1.4486, 1.2726]], grad_fn=<MmBackward0>)


In [49]:
#using nn.linear as it has he/xavier weight initializaton

class SelfAttention_v2(nn.Module):
    def __init__(self,d_in,d_out,bias_=False):
        super().__init__()

        self.w_keys_v2=nn.Linear(d_in,d_out,bias=bias_)
        self.w_query_v2=nn.Linear(d_in,d_out,bias=bias_)
        self.w_values_v2=nn.Linear(d_in,d_out,bias=bias_)

    def forward(self,x):
        keys_matrix_v2=self.w_keys_v2(x)
        values_matrix_v2=self.w_values_v2(x)
        query_matrix_v2=self.w_query_v2(x)

        attention_scores_matirx=query_matrix_v2 @ keys_matrix_v2.T

        atteniton_weights=torch.softmax(
            attention_scores_matirx / keys_matrix_v2.shape[-1]**0.5,dim=-1
        )
        context_vectors_v2=atteniton_weights @ values_matrix_v2

        return context_vectors_v2







torch.manual_seed(69)

sa_v2=SelfAttention_v2(d_in,d_out)
print(sa_v2(inputs))

tensor([[-0.2243,  0.0456, -0.0402],
        [-0.2239,  0.0622, -0.0334],
        [-0.2226,  0.0685, -0.0314],
        [-0.2230,  0.0851, -0.0246],
        [-0.2225,  0.0700, -0.0307],
        [-0.2241,  0.0335, -0.0454]], grad_fn=<MmBackward0>)


In [61]:
queries= sa_v2.w_query_v2(inputs)
keys= sa_v2.w_query_v2(inputs)
values=sa_v2.w_values_v2(inputs)

attention_scores=keys @ values.T
attention_weights=torch.softmax(
    attention_scores / keys.shape[-1] ** 0.5 ,dim=-1
)

context_vectors = attention_weights @ values


In [64]:
attention_weights.sum(dim=-1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
       grad_fn=<SumBackward1>)

In [65]:
device = torch.device("mps") 

In [66]:
device

device(type='mps')

In [81]:
mac1=torch.tensor(torch.rand(11,100)).to(device)
mac2=torch.tensor(torch.rand(11,100)).to(device)


/var/folders/hp/y1d826dx5fb1405ppnjjm4700000gn/T/ipykernel_4906/1546787270.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mac1=torch.tensor(torch.rand(11,100)).to(device)
/var/folders/hp/y1d826dx5fb1405ppnjjm4700000gn/T/ipykernel_4906/1546787270.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  mac2=torch.tensor(torch.rand(11,100)).to(device)


In [87]:
context_length = attention_scores.shape[0]
mask = torch.tril( 
    torch.ones(context_length,context_length)
)

In [88]:
mask

tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])

In [102]:
masked_attn=attention_scores * mask

In [103]:
masked_attn

tensor([[-0.0590, -0.0000,  0.0000, -0.0000,  0.0000,  0.0000],
        [-0.0598, -0.0513,  0.0000, -0.0000,  0.0000, -0.0000],
        [-0.0502, -0.0436, -0.1549, -0.0000, -0.0000, -0.0000],
        [-0.1310, -0.0710, -0.2404, -0.1792, -0.0000, -0.0000],
        [-0.0197, -0.0217, -0.0984, -0.1233, -0.0645, -0.0000],
        [-0.0470, -0.0808,  0.0925, -0.1022,  0.0957,  0.0860]],
       grad_fn=<MulBackward0>)

In [107]:
masked_attn = masked_attn / masked_attn.sum(-1,keepdim=True)

In [108]:
masked_attn

tensor([[ 1.0000,  0.0000, -0.0000,  0.0000, -0.0000,  0.0000],
        [ 0.6874,  0.3126, -0.0000,  0.0000, -0.0000, -0.0000],
        [ 0.4561,  0.2101,  0.3338,  0.0000,  0.0000, -0.0000],
        [ 0.5398,  0.1553,  0.2348,  0.0700,  0.0000, -0.0000],
        [ 0.2532,  0.1477,  0.2997,  0.1503,  0.1492, -0.0000],
        [ 0.2681,  0.2446, -0.1251,  0.0553, -0.0982,  0.6553]],
       grad_fn=<DivBackward0>)

In [109]:
masked_attn.sum(-1)

tensor([1.0000, 1.0000, 1.0000, 1.0000, 1.0000, 1.0000],
       grad_fn=<SumBackward1>)